config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'contact' =>'contacts#contact'
  get 'confirm' => 'contacts#confirm'
  get 'done' => 'contacts#done'

  get 'about' => 'homes#about'
  get 'performance' => 'homes#performance'
  get 'access' => 'homes#access'
  get 'privacy_policy' => 'homes#privacy_policy'

  resources :contacts, only: [:create]

  root 'homes#top'

  namespace :admin do
    get 'top' => 'homes#top'
    get 'today' => 'contacts#today'
    resources :contacts
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :user_name, presence: true
  validates :ruby, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
  validates :tel, presence: true, format: { with: /\A\d{10}$|^\d{11}\z/ }
  validates :contents, presence: true

end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_action :authenticate_admin_user!

  def today
    @contacts = Contact.where(created_at: Time.zone.now.all_day).page(params[:page]).reverse_order.per(10)
  end

  def index
    @contacts = Contact.page(params[:page]).reverse_order.per(10)
  end

  def show
    @contact = Contact.find(params[:id])
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin_user!


  def top
    @contacts = Contact.where(created_at: Time.zone.now.all_day)
  end

end

app/controllers/admin_users/confirmations_controller.rb
# frozen_string_literal: true

class AdminUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class AdminUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin_users/passwords_controller.rb
# frozen_string_literal: true

class AdminUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin_users/registrations_controller.rb
# frozen_string_literal: true

class AdminUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin_users/sessions_controller.rb
# frozen_string_literal: true

class AdminUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin_users/unlocks_controller.rb
# frozen_string_literal: true

class AdminUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected
  def after_sign_in_path_for(resource)
    case resource
    when AdminUser
      admin_top_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :admin_user
      new_admin_user_session_path
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def contact
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to done_path, notice: "フォームは送信されました。"
    else
      redirect_to contact_path, notice: "フォームの送信に失敗しました。"
    end
  end

  def confirm
    @contact = Contact.new
    @contact.name = params[:name]
    @contact.ruby = params[:ruby]
    @contact.company_name = params[:company_name]
    @contact.email = params[:email]
    @contact.tel = params[:tel]
    @contact.contents = params[:contents]
    if @contact.valid?
      render :action => 'done'
    else
      render :action => 'contact'
    end
  end

  def done
    @contact = Contact.new(contact_params)
    if params[:back]
      render :action => 'contact'
    else
      render :action => 'done'
    end
  end

  private

  def contact_params
    params.permit(:user_name, :ruby, :company_name, :email, :tel, :contents)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  

end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/contacts/index.html.erb
<%= stylesheet_link_tag 'contact' %>

<div class="admin_index">
  <div class="container">
    <h2>お問い合わせ一覧</h2>
    <table class="admin_index_table">
      <thead>
        <tr>
          <th>日時</th>
          <th>お名前</th>
          <th>企業名</th>
          <th>内容</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
        <tr>
          <td><%= l contact.created_at %></td>
          <td><%= contact.user_name %></td>
          <td><%= contact.company_name %></td>
          <td><%= contact.contents.truncate(50) %></td>
          <td><%= link_to "show", admin_contact_path(contact.id) %></td>
        </tr>
        <% end %>
        <%= paginate @contacts %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/contacts/show.html.erb
<%= stylesheet_link_tag 'contact' %>


<div class="admin_show_page">
  <div class="container">
    <h2>お問い合わせ詳細</h2>
    <table class="admin_show_table">
      <tbody>
        <tr>
          <th>日時</th>
          <td><%= l @contact.updated_at %></td>
        </tr>
        <tr>
          <th>お名前</th>
          <td><%= @contact.user_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @contact.ruby %></td>
        </tr>
        <tr>
          <th>企業名</th>
          <td><%= @contact.company_name %></td>
        </tr>
        <tr>
          <th>e-mail</th>
          <td><%= @contact.email %></td>
        </tr>
        <tr>
          <th>TEL</th>
          <td><%= @contact.tel %></td>
        </tr>
        <tr>
          <th>内容</th>
          <td><%= @contact.contents %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/contacts/today.html.erb
<%= stylesheet_link_tag 'contact' %>

<div class="admin_top">
  <div class="container">
    <h2>本日のお問い合わせ一覧</h2>
    <table class="admin_index_table">
      <thead>
        <tr>
          <th>日時</th>
          <th>お名前</th>
          <th>企業名</th>
          <th>内容</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
        <tr>
          <td><%= l contact.created_at %></td>
          <td><%= contact.user_name %></td>
          <td><%= contact.company_name %></td>
          <td><%= contact.contents.truncate(50) %></td>
          <td><%= link_to "show", admin_contact_path(contact.id) %></td>
        </tr>
        <% end %>
        <%= paginate @contacts %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="admin_top">
  <div class="container">
    <h2 class="">管理者画面</h2>
    <div class="row">
      <h3 class="ml-5">本日のお問い合わせ　　<%= link_to @contacts.count, admin_today_path %>件</h3>
    </div>
  </div>
</div>

app/views/contacts/comfirm.html.erb
<div class="form_page">
  <h2>確認</h2>
  <%= form_with(model: @contact, local: true, url: {action: 'create'}) do |f| %>
    <table>
      <tbody>
        <tr>
          <td>お名前</td>
          <td>
            <%= @contact.name %>
            <%= f.hidden_field :name, :value => @contact %>
          </td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td>
            <%= @contact.ruby %>
            <%= f.hidden_field :ruby, :value => @contact %>
          </td>
        </tr>
        <tr>
          <td>企業名</td>
          <td>
            <%= @contact.company_name %>
            <%= f.hidden_field :company_name, :value => @contact %>
          </td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td>
            <%= @contact.email %>
            <%= f.hidden_field :email, :value => @contact %>
          </td>
        </tr>
        <tr>
          <td>TEL</td>
          <td>
            <%= @contact.tel %>
            <%= f.hidden_field :tel, :value => @contact %>
          </td>
        </tr>
        <tr>
          <td>内容</td>
          <td>
            <%= @contact.contacts %>
            <%= f.hidden_field :contacts, :value => @contact %>
          </td>
        </tr>
      </tbody>
    </table>
    <%= link_to "戻る", :back %>
    <%= f.submit '送信', class: "btn btn-success btn-lg" %>
  <% end %>
</div>

app/views/contacts/confirm.html.erb
<div class="form_page">
  <h2>確認</h2>
  <%= form_with(model: @contact, local: true, url: {action: 'create'}) do |f| %>
    <table>
      <tbody>
        <tr>
          <td>お名前</td>
          <td>
            <%= @contact.name %>
            <%= f.hidden_field :name, :value => @contact %>
          </td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td>
            <%= @contact.ruby %>
            <%= f.hidden_field :ruby, :value => @contact %>
          </td>
        </tr>
        <tr>
          <td>企業名</td>
          <td>
            <%= @contact.company_name %>
            <%= f.hidden_field :company_name, :value => @contact %>
          </td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td>
            <%= @contact.email %>
            <%= f.hidden_field :email, :value => @contact %>
          </td>
        </tr>
        <tr>
          <td>TEL</td>
          <td>
            <%= @contact.tel %>
            <%= f.hidden_field :tel, :value => @contact %>
          </td>
        </tr>
        <tr>
          <td>内容</td>
          <td>
            <%= @contact.contacts %>
            <%= f.hidden_field :contacts, :value => @contact %>
          </td>
        </tr>
      </tbody>
    </table>
    <%= link_to "戻る", :back %>
    <%= f.submit '送信', class: "btn btn-success btn-lg" %>
  <% end %>
</div>

app/views/contacts/contact.html.erb
<%= stylesheet_link_tag 'contact' %>

<div class="form_page">
  <div class="container">
    <h2>お問い合わせ</h2>
    <%= form_with url: contacts_path , method: :post, local: true do |f| %>
      <table class="FormTable">
        <tbody>
          <tr>
            <td class="cp_iptxt">
              <%= f.text_field :user_name, class: "form-control iptxt", type:"text", placeholder:"お名前※" %>
              <i class="fa fa-user fa-lg fa-fw" aria-hidden="true"></i>
            </td>
          </tr>
          <tr>
            <td class="cp_iptxt">
              <%= f.text_field :ruby, class: "form-control iptxt", type:"text", placeholder:"フリガナ(全角カタカナ)※" %>
              <i class="fas fa-pen fa-lg fa-fw" aria-hidden="true"></i>
            </td>
          </tr>
          <tr>
            <td class="cp_iptxt">
              <%= f.text_field :company_name, class: "form-control iptxt", type:"text", placeholder:"企業名" %>
              <i class="fas fa-building fa-lg fa-fw" aria-hidden="true"></i>
            </td>
          </tr>
          <tr>
            <td class="cp_iptxt">
              <%= f.text_field :email, class: "form-control iptxt", type:"text", placeholder:"e-mail※" %>
              <i class="fa fa-envelope fa-lg fa-fw" aria-hidden="true"></i>
            </td>
          </tr>
          <tr>
            <td class="cp_iptxt">
              <%= f.text_field :tel, class: "form-control iptxt", type:"text", placeholder:"TEL(ハイフンなし)※" %>
              <i class="fas fa-phone fa-lg fa-fw" aria-hidden="true"></i>
            </td>
          </tr>
          <tr>
            <td class="cp_iptxt">
              <%= f.text_area :contents, class: "form-control iptxt", placeholder:"内容※" %>
              <i class="fas fa-comments fa-lg fa-fw" aria-hidden="true"></i>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="buttons-coll">
        <%= f.submit "送信", class: "custom-btn"%>
      </div>
    <% end %>
  </div>
</div>

app/views/contacts/done.html.erb
<%= stylesheet_link_tag 'contact' %>

<div class="form_page">
  <div class="container">
    <h2 class="done-message">フォームの送信に成功しました。</h2>
    <%= link_to "トップに戻る", root_path, class:"back-btn" %>
  </div>
</div>

app/views/homes/about.html.erb
<%= stylesheet_link_tag 'home' %>


<div class="about_page">
  <div class="container">
    <h2>会社概要</h2>
    <table>
      <tbody>
        <tr>
          <th>会社名</th>
          <td>株式会社プライムワン</td>
        </tr>
        <tr>
          <th>創業</th>
          <td>２００７年８月</td>
        </tr>
        <tr>
          <th>資本金</th>
          <td>1,000,000円</td>
        </tr>
        <tr>
          <th>代表取締役</th>
          <td>岡田　隆</td>
        </tr>
        <tr>
          <th>本社所在地</th>
          <td>〒629-0153<br>京都府南丹市八木町八木嶋町ノ坪11-1</td>
        </tr>
        <tr>
          <th>京都営業所</th>
          <td>〒615-0841<br>京都府京都市右京区西京極火打畑町4</td>
        </tr>
        <tr>
          <th>事業内容</th>
          <td>
            人材派遣業<br>
            各種請負業<br>
            各種コンサルティング業<br>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/homes/access.html.erb
<div class="access_page">
  <h2>アクセス</h2>
  <div class="maps">
    <h3>プライムワン本社</h3>
    <div class="map-01" id='map-01'></div>
    <div class="row map01">
      <table>
        <tbody>
          <tr>
            <td>所在地</td>
            <td>〒629-0153<br>京都府南丹市八木町八木嶋町ノ坪11-1</td>
          </tr>
          <tr>
            <td>TEL</td>
            <td>0771-43-2088</td>
          </tr>
          <tr>
            <td>FAX</td>
            <td>0771-42-4211</td>
          </tr>
          <tr>
            <td>営業時間</td>
            <td>月～金曜日／9：00～17:00</td>
          </tr>
          <tr>
            <td>定休日</td>
            <td>土・日・祝</td>
          </tr>
          <tr>
            <td>最寄駅</td>
            <td>JR嵯峨野線 八木駅</td>
          </tr>
        </tbody>
      </table>
    </div>
    <h3>京都営業所</h3>
    <div class="map-01" id='map-02'></div>
    <table>
      <tbody>
        <tr>
          <td>所在地</td>
          <td>〒615-0841<br>京都府京都市右京区西京極火打畑町4</td>
        </tr>
        <tr>
          <td>TEL</td>
          <td>075-874-3587</td>
        </tr>
        <tr>
          <td>FAX</td>
          <td>075-311-5420</td>
        </tr>
        <tr>
          <td>営業時間</td>
          <td>月～金曜日 / 9：00～17:00</td>
        </tr>
        <tr>
          <td>定休日</td>
          <td>土・日・祝日</td>
        </tr>
        <tr>
          <td>最寄駅</td>
          <td>JR嵯峨野線 八木駅</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/homes/privacy_policy.html.erb
<div class="privacy_policy_page">
  <div class="container">
    <h2>プライバシーポリシー</h2>
    <div class="text_contents">
      <p>個人情報の取り扱いについて<br>
        <br>
        個人情報とは、個人に関する情報であり、氏名、生年月日、性別、電話番号、電子メールアドレス、<br>
        職業、勤務先等、特定の個人を識別し得る情報をいいます。<br>
        <br>
        （個人情報の収集・利用）<br>
        当社は、以下の目的のため、その範囲内においてのみ、個人情報を収集・利用いたします。<br>
        当社による個人情報の収集・利用は、お客様の自発的な提供によるものであり、<br>
        お客様が個人情報を提供された場合は、当社が本方針に則って個人情報を利用する<br>
        ことをお客様が許諾したものとします。<br>
        ①ご注文された当社の商品をお届けするうえで必要な業務<br>
        ②新商品の案内など、お客様に有益かつ必要と思われる情報の提供<br>
        ③業務遂行上で必要となる当社からの問い合わせ、確認、およびサービス向上のための意見収集<br>
        ④各種のお問い合わせ対応<br>
        ⑤弊社の広告宣伝またはマーケティングなど<br>
        ・お客様へ各種メールマガジンなどの情報提供。<br>
        ・当社からお客様へ電話・ダイレクトメールにて、商品・サービス提供などのご案内。<br>
        ・お客様によるサービスの利用を分析し、サービスの改善を図る為。<br>
        <br>
        （個人情報の第三者提供）<br>
        当社は、法令に基づく場合等正当な理由によらない限り、事前に本人の同意を得ることなく、<br>
        個人情報を第三者に開示・提供することはありません。<br>
        <br>
        （委託先の監督）<br>
        当社は、お客様へ商品やサービスを提供する等の業務遂行上、個人情報の一部を外部の委託先へ<br>
        提供する場合があります。その場合、業務委託先が適切に個人情報を取り扱うように管理いたします。<br>
        <br>
        （個人情報の管理）<br>
        <br>
        当社は、個人情報の漏洩、滅失、毀損等を防止するために、個人情報保護管理責任者を設置し、<br>
        十分な安全保護に努め、また、個人情報を正確に、また最新なものに保つよう、お預かりした<br>
        個人情報の適切な管理を行います。<br>
        <br>
        （情報内容の照会、修正または削除）<br>
        当社は、お客様が当社にご提供いただいた個人情報の照会、修正または削除を希望される場合は、<br>
        ご本人であることを確認させていただいたうえで、合理的な範囲ですみやかに対応させていただきます。<br>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrimeoneHp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA6oI97dPNTskpK8GG5eU-T9ijOmLNAKG4&callback=initMap" async defer></script>
  </head>

  <body>
    <div class="wrapper">
      <header class="navbar">
        <div class="container">
          <% if admin_user_signed_in? %>
          <nav class="logo_space">
            <%= link_to admin_top_path do %>
            <%= image_tag "logo_01.png", :width => "270", :height => "50" %>
            <% end %>
          </nav>
          <nav class="nav">
            <ul class="nav p-4">
              <li class="nav-item mr-3"><%= link_to "ホーム", admin_top_path, class: "btn btn-nav" %></li>
              <li class="nav-item mr-3"><%= link_to "本日の問い合わせ", admin_today_path, class: "btn btn-nav" %></li>
              <li class="nav-item mr-3"><%= link_to "問い合わせ", admin_contacts_path, class: "btn btn-nav" %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete, class: "btn btn-nav" %></li>
            </ul>
          </nav>
          <% else %>
          <nav class="logo_space">
            <%= link_to root_path do %>
            <%= image_tag "logo_01.png", :width => "270", :height => "50" %>
            <% end %>
          </nav>
          <nav class="nav">
            <ul class="nav p-4">
              <li class="nav-item mr-3"><%= link_to "ホーム", root_path, class: "btn btn-nav" %></li>
              <li class="nav-item mr-3"><%= link_to "概要", about_path, class: "btn btn-nav" %></li>
              <li class="nav-item mr-3"><%= link_to "お問い合わせ", contact_path, class: "btn btn-nav" %></li>
              <li class="nav-item"><%= link_to "プライバシーポリシー", privacy_policy_path, class: "btn btn-nav" %></li>
            </ul>
          </nav>
          <% end %>
        </div>
      </header>
      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <div class="main">
        <%= yield %>
      </div>
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-3 logo_space">
              <%= link_to root_path do %>
                <%= image_tag "logo_01.png", :width => "270", :height => "50" %>
              <% end %>
            </div>
            <div class="col-1"></div>
            <div class="col-8 navbar">
              <nav class="nav">
                <ul class="nav p-4">
                  <li class="nav-item mr-3"><%= link_to "Home", root_path, class: "btn btn-nav" %></li>
                  <li class="nav-item mr-3"><%= link_to "About", about_path, class: "btn btn-nav" %></li>
                  <li class="nav-item mr-3"><%= link_to "Contact", contact_path, class: "btn btn-nav" %></li>
                  <li class="nav-item"><%= link_to "プライバシーポリシー", privacy_policy_path, class: "btn btn-nav" %></li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="copyright">
            <p>Copyright©2020-2020 株式会社プライムワン All Rights Reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>